server:
  name: "notary-server"
  host: "0.0.0.0"
  port: 7047

notarization:
  max-transcript-size: 16384

notary-signature:
  private-key-pem-path: "./fixture/notary/notary.key"

tracing:
  default-level: DEBUG
